# Generated by Django 3.2.16 on 2022-12-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
