# Generated by Django 3.2.16 on 2022-12-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Records', '0002_user_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
